name: run-linter
on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      - '!master'   # excludes master

jobs:
  push:
    name: Pylint checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          fetch-depth: '0'

      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: git checkout test

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: >-
          python -m
          pip install
          pylint
          --user

      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep .py | xargs)"

      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - run: /home/runner/.local/bin/pylint ${{ steps.getfile.outputs.files }}