name: autorelease
on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  build:
    if: github.event.pull_request.merged == true && contains(toJSON(github.event.pull_request.labels.*.name), '"autorelease"')
    runs-on: ubuntu-latest
    env:
      manifest_file: 'manifest.yml'
      changelog_file: 'CHANGES.rst'
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: get version
        id: version
        run: |
          sed -n 's/^version:\s\(.*\)$/\1/p' ${{ env.manifest_file }} \
          | xargs -i echo "::set-output name=version::{}"
      - name: echo version and changelog
        run: |
          echo "${{ steps.version.outputs.version}}"
          echo "${{ steps.changelog.outputs.changelog }}"
      - name: Create Release
        uses: ncipollo/release-action@v1.4.0
        with:
          name: ${{ steps.version.outputs.version }}
          tag: v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          # An optional tag for the release. If this is omitted the git ref will be used (if it is a tag).
          token: ${{ secrets.GITHUB_TOKEN }}