name: test
on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      - '!master'   # excludes master

jobs:
  push:
    name: Push Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: git checkout test
      - run: echo sdadw > zzz
      - name: Add and commit
        uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          # The name of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_name: Your Name

          # The email of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_email: mail@example.com

          # The message for the commit
          # Default: 'Commit from GitHub Actions'
          message: 'Your commit message'

        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
      - run: black .

