name: unittests

on:
  push:
    branches:
      - master

jobs:
  push:
    name: Python Pylin GitHub Action
    uses: fylein/python-pytest-github-action@v1
    with:
      args: pip3 install -r requirements.txt && pytest tests/
