name: unittests

on:
  push:
    branches:
      - master

jobs:
  push:
    name: Push Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
         python-version: 3.7
      - run: mkdir -p artifact
      - run: pip3 install -r requirements.txt && pytest tests --junitxml=artifact/unittest.results.xml
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: artifact